In [15]:
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [17]:
print(iris.data[:5])      # first 5 flower measurements
print(iris.target[:5])    # their species labels
print(iris.target_names)  # ['setosa', 'versicolor', 'virginica']

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']


In [24]:
iris = load_iris()
x = iris.data[:100 , :2] # 0 to 99 row , 0 1 col
y = iris.target[:100]

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)
def sigmoidFx(x):
    return 1 / (1 + np.exp(-x))

W = np.zeros(2)
b = 0 
lr = 0.1 

for _ in range(1000):
    z =x_train @ W + b # vector calculation 
    y_pred = sigmoidFx(z)
    grad_w = x_train.T @ (y_pred - y_train) / len(y_train)
    grad_b = np.mean(y_pred - y_train)
    W -= lr*grad_w 
    b -= lr* grad_b


#test 
z_test = x_test @ W + b
y_pred_test = (sigmoidFx(z_test) > 0.5).astype(int)
print("Accuracy:", accuracy_score(y_test, y_pred_test))

Accuracy: 1.0
